$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake-workflows alignment configuration

properties:
  bam_sorter:
    description: which sorting software to use
    default: samtools
    enum: [sambamba, samtools]
    type: string
  bam_sort_order:
    description: sort order of aligned reads
    default: coordinate
    enum: [queryname, coordinate]
    type: string
