language: python
python:
  - 3.6

install:
  - sudo apt-get update

  # install conda if not cached
  - if [ ! -d $HOME/miniconda/bin/ ]; then
      conda_cached=false;
      rm -rf $HOME/miniconda;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda

  # create snakemake env
  - if [ "$conda_cached" = false ]; then
      conda env create -f envs/snakemake-workflows.yaml;
    fi

script:
  - source activate snakemake-workflows

  # Do some dry runs
  - for i in {1..3}; do snakemake -s workflows/download_fastq/Snakefile --directory workflows/download_fastq -n -j 48 && break; done
  - for i in {1..3}; do snakemake -s workflows/alignment/Snakefile      --directory workflows/alignment      -n -j 48 && break; done
  - for i in {1..3}; do snakemake -s workflows/atac_seq/Snakefile       --directory workflows/atac_seq       -n -j 48 && break; done

# speedup the slow build of our environment
cache:
    directories:
     - ${HOME}/miniconda
