# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
# fastq_dir: (default is inside result_dir) # where to look for or download the fastqs



# contact info for multiqc report and trackhub
email: yourmail@here.com

# how to handle replicates
technical_replicates: merge

## filtering after alignment
#remove_blacklist: True
#remove_mito: True
#tn5_shift: True
#min_mapping_quality: 30
#only_primary_align: True

# use 'our' default parameters
quantifier: kallistobus
barcodefile: "barcodes.txt"
protocol: celseq