# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
# fastq_dir: (default is inside result_dir) # where to look for or download the fastqs



# contact info for multiqc report and trackhub
email: yourmail@here.com

# how to handle replicates
technical_replicates: merge

# scRNA options
quantifier: kallistobus
barcodefile: "barcodes.txt"
# currently only supported protocol is celseq, please make issue on github
# if you want another supported: https://github.com/vanheeringen-lab/seq2science
protocol: celseq
