channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::bwa=0.7.17
  - bioconda::samtools=1.9
  - bioconda::picard=2.9.2
  - conda-forge::cpulimit=0.2
  - bioconda::norns=0.1.4
  - bioconda::sambamba=0.7.0
