# tab-separated file of the samples
samples: samples.tsv


# pipeline file locations
result_dir: ./  # where to store results
genome_dir: ../../Jenkins  # where to look for or download the genomes
fastq_dir: ../../Jenkins/test_fastq


# produce bams, bigwigs and QC statistics?
run_alignment: False

# which method to use in order to generate the counts (salmon or star)
quantifier: star # star or salmon


## differential expression analysis
#diffexp: # which analysis to use (DESeq2 or None, default: None)
#  deseq2:
#    DE_params:
#      multiple_testing_procedure: IWH # default is BH
#      alpha_value: 0.05
#      shrinkage_estimator: apeglm
#    contrasts:
#      - 'disease_control_disease'
#      - 'stage_1_2'
#      - 'stage_1_all'
