$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake-workflows configuration

properties:
  # workflow samples
  samples:
    description: tab-separated file specifying the samples to run through the workflow
    default: samples.tsv
    type: string

  # paths
  rule_dir:
    description: directory where to find the workflow rules
    default: ../../rules
    type: string
  result_dir:
    description: where to store all the pipeline's results
    default: ./
    type: string
  genome_dir:
    description: where to store the pipeline's genome assemblies. NOTE that this is not inside the result_dir
    default: ./
    type: string
  log_dir:
    description: directory where to store the logs
    default: log
    type: string
  benchmark_dir:
    description: directory where to store the logs
    default: benchmark
    type: string
  sra_dir:
    description: directory inside the result dir where to store the workflow sras
    default: sra
    type: string
  fastq_dir:
    description: directory inside the result dir where to store the workflow fastqs
    default: FASTQ
    type: string
  trimmed_dir:
    description: directory inside the result dir where to store the workflow trimmed fastqs
    default: FASTQ
    type: string
  trimmedqc_dir:
    description: directory inside the result dir where to store the workflow trimming quality controls
    default: trimmed_qc
    type: string
  bwa_dir:
    description: directory inside the result dir where to store the workflow bwa output
    default: bwa
    type: string
  dedup_dir:
    description: directory inside the result dir where to store the workflow deduplicated alignment
    default: dedup
    type: string

  # NCBI e-utilities key
  ncbi_key:
    description: e-utilities key for faster lookup interval
    type: string
  ncbi_requests:
    description: the number of lookups per second the key permits
    default: 3
    type: integer

  # downloading through ascp
  ascp_path:
    description: the pipeline supports downloading through ascp if this variable is set.
    type: string
    default: "NO_ASCP"
  ascp_key:
    description: the public key of ascp
    type: string
    default: "NO_ASCP_KEY"

  # fastq-dump parameters
  split:
    description: fastq-dump parameters when splitting reads (paired-end)
    default: --split-files --skip-technical --dumpbase --readids --clip --read-filter pass --defline-seq '@$ac.$si.$sg/$ri' --defline-qual '+'
    type: string
  splot:
    description: fastq-dump parameters when splotting reads (single-end)
    default: --split-spot  --skip-technical --dumpbase --readids --clip --read-filter pass --defline-seq '@$ac.$si.$sg/$ri' --defline-qual '+'
    type: string

  # filename conventions
  fqext1:
    description: filename suffix when handling paired-end data, describing the forward read
    default: pass_1
    type: string
  fqext2:
    description: filename suffix when handling paired-end data, describing the reverse read
    default: pass_2
    type: string
  fqsuffix:
    description: file descriptor for fastq files (often fastq or fq)
    default: fastq
    type: string

  # trim_galore parameters
  trim_galore:
    description: trim_galore settings (note that the adapter is autodetected, so you do not have to set it here)
    default: --quality 10 --length 20 --consider_already_trimmed 10
    type: string

  # aligner
  aligner:
    description: which aligner to use
    default: bwa
    enum: [bowtie2, bwa, hisat2]
    type: string

  # bwa alignment parameters
  bwa_algo:
    description: the algorithm bwa index uses for alignment
    default: bwtsw
    type: string

  # bam sorting
  bam_sorter:
    description: which sorting software to use
    default: samtools
    enum: [sambamba, samtools]
    type: string
  bam_sort_order:
    description: sort order of aligned reads
    default: coordinate
    enum: [queryname, coordinate]
    type: string

  # samtools index
  samtools_index:
    description: samtools index settings
    default: ''
    type: string

  # picard markduplicates
  markduplicates:
    description: the parameters of picard markduplicates
    default: REMOVE_DUPLICATES=false -Xms4G -Xmx6G MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=999
    type: string

  # peak caller algorithms
  peak_caller:
    description: which peak caller(s) to use. Currently macs2 (default), genrich, and hmmratac are supported.
    type: array

  validated:
    description: for internal use only. Is used to check if the configuration has been validated (yet).
    type: boolean
    default: true
#    genrich:
#      description: genrich peak caller
#      default: ''
#      type: string
#    macs2:
#      description: macs2 peak caller
#      type: string


#required:
#  - sample
#  - assembly
