$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake-workflows peak calling configuration

properties:
  # peak caller algorithms
  peak_caller:
    description: which peak caller(s) to use. Currently macs2 (default) and genrich are supported.
    type: array
    default: [macs2]
