# tab-separated file of the samples
samples: samples.tsv


# pipeline file locations
result_dir: ./  # where to store results
genome_dir: ./  # where to look for or download the genomes


# peak callers (supported peak callers are macs2 & genrich)
peak_caller:
  - macs2:
      --shift -100 --extsize 200 --nomodel --keep-dup 1 --buffer-size 10000
  - genrich:
      -y -j


# when calling genrich peaks the alignment has to be queryname sorted
bam_sorter: sambamba
bam_sort_order: queryname


fqext1: R1
fqext2: R2